### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by abbieadell** [davidfoxcroft/lsj-book#43]
I am on MAC OS and i am unable to download the textbook. I click the download button and nothing happens

**Comment by davidfoxcroft** [comment]
Hi, I've just checked and it works for me. Maybe try a different browser? Here is the direct download link for the pdf version: [https://davidfoxcroft.github.io/lsj-book/learning-statistics-with-jamovi.pdf](https://davidfoxcroft.github.io/lsj-book/learning-statistics-with-jamovi.pdf)

Otherwise the html version can be found via [www.learnnstatswithjamovi.com](www.learnstatswithjamovi.com)

**Comment by Speldosa** [comment]
On this topic, I would suggest making the PDF link more visible. I searched the site for about 10 minutes before finally fining it after clicking the top of the loj-book part of the homepage and there seeing a small PDF symbol. It was only thanks to this issue that I was able to locate it from the start (I was ready to download everything from Github and compile it myself).

I would suggest putting the links directly in the text instead, preferably already on the landing page.
